version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "America/Sao_Paulo"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/front"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:15"
      timezone: "America/Sao_Paulo"
    groups:
      npm-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "nuget"
    directory: "/back"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:30"
      timezone: "America/Sao_Paulo"
    groups:
      nuget-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "dotnet-sdk"
    directory: "/back"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:45"
      timezone: "America/Sao_Paulo"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "docker"
    directory: "/back"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "docker"
    directory: "/front"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:15"
      timezone: "America/Sao_Paulo"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:30"
      timezone: "America/Sao_Paulo"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
