// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VibeCheckAPI_Dotnet8.Data.Context;

#nullable disable

namespace VibeCheckAPI_Dotnet8.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251203024254_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VibeCheckAPI_Dotnet8.Models.Avaliacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataExpiracao")
                        .HasColumnType("datetime2");

                    b.Property<int>("TipoAvaliacao")
                        .HasColumnType("int");

                    b.Property<int>("TurmaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TurmaId");

                    b.ToTable("Avaliacoes");
                });

            modelBuilder.Entity("VibeCheckAPI_Dotnet8.Models.Emocao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ValorNumerico")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ValorNumerico")
                        .IsUnique();

                    b.ToTable("Emocoes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Emoji = "😠",
                            Titulo = "Irritado",
                            ValorNumerico = 1
                        },
                        new
                        {
                            Id = 2,
                            Emoji = "😢",
                            Titulo = "Triste",
                            ValorNumerico = 2
                        },
                        new
                        {
                            Id = 3,
                            Emoji = "😰",
                            Titulo = "Ansioso",
                            ValorNumerico = 3
                        },
                        new
                        {
                            Id = 4,
                            Emoji = "😞",
                            Titulo = "Desmotivado",
                            ValorNumerico = 4
                        },
                        new
                        {
                            Id = 5,
                            Emoji = "😐",
                            Titulo = "Indiferente",
                            ValorNumerico = 5
                        },
                        new
                        {
                            Id = 6,
                            Emoji = "😮",
                            Titulo = "Surpreso",
                            ValorNumerico = 6
                        },
                        new
                        {
                            Id = 7,
                            Emoji = "😊",
                            Titulo = "Feliz",
                            ValorNumerico = 7
                        },
                        new
                        {
                            Id = 8,
                            Emoji = "😄",
                            Titulo = "Muito Feliz",
                            ValorNumerico = 8
                        },
                        new
                        {
                            Id = 9,
                            Emoji = "😍",
                            Titulo = "Apaixonado",
                            ValorNumerico = 9
                        });
                });

            modelBuilder.Entity("VibeCheckAPI_Dotnet8.Models.RegistroEmocional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlunoId")
                        .HasColumnType("int");

                    b.Property<int>("AvaliacaoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EmocaoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("AvaliacaoId");

                    b.HasIndex("EmocaoId");

                    b.ToTable("RegistrosEmocionais");
                });

            modelBuilder.Entity("VibeCheckAPI_Dotnet8.Models.Turma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Turmas");
                });

            modelBuilder.Entity("VibeCheckAPI_Dotnet8.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GoogleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleId")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasDiscriminator<string>("TipoUsuario").HasValue("Usuario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("VibeCheckAPI_Dotnet8.Models.Aluno", b =>
                {
                    b.HasBaseType("VibeCheckAPI_Dotnet8.Models.Usuario");

                    b.Property<int?>("TurmaId")
                        .HasColumnType("int");

                    b.HasIndex("TurmaId");

                    b.HasDiscriminator().HasValue("Aluno");
                });

            modelBuilder.Entity("VibeCheckAPI_Dotnet8.Models.Professor", b =>
                {
                    b.HasBaseType("VibeCheckAPI_Dotnet8.Models.Usuario");

                    b.HasDiscriminator().HasValue("Professor");
                });

            modelBuilder.Entity("VibeCheckAPI_Dotnet8.Models.Avaliacao", b =>
                {
                    b.HasOne("VibeCheckAPI_Dotnet8.Models.Turma", "Turma")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("VibeCheckAPI_Dotnet8.Models.RegistroEmocional", b =>
                {
                    b.HasOne("VibeCheckAPI_Dotnet8.Models.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId");

                    b.HasOne("VibeCheckAPI_Dotnet8.Models.Avaliacao", "Avaliacao")
                        .WithMany("RegistrosEmocionais")
                        .HasForeignKey("AvaliacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VibeCheckAPI_Dotnet8.Models.Emocao", "Emocao")
                        .WithMany("RegistrosEmocionais")
                        .HasForeignKey("EmocaoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Aluno");

                    b.Navigation("Avaliacao");

                    b.Navigation("Emocao");
                });

            modelBuilder.Entity("VibeCheckAPI_Dotnet8.Models.Turma", b =>
                {
                    b.HasOne("VibeCheckAPI_Dotnet8.Models.Professor", "Professor")
                        .WithMany("Turmas")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("VibeCheckAPI_Dotnet8.Models.Aluno", b =>
                {
                    b.HasOne("VibeCheckAPI_Dotnet8.Models.Turma", "Turma")
                        .WithMany("Alunos")
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("VibeCheckAPI_Dotnet8.Models.Avaliacao", b =>
                {
                    b.Navigation("RegistrosEmocionais");
                });

            modelBuilder.Entity("VibeCheckAPI_Dotnet8.Models.Emocao", b =>
                {
                    b.Navigation("RegistrosEmocionais");
                });

            modelBuilder.Entity("VibeCheckAPI_Dotnet8.Models.Turma", b =>
                {
                    b.Navigation("Alunos");

                    b.Navigation("Avaliacoes");
                });

            modelBuilder.Entity("VibeCheckAPI_Dotnet8.Models.Professor", b =>
                {
                    b.Navigation("Turmas");
                });
#pragma warning restore 612, 618
        }
    }
}
